### ISSUE TITLE
Not recursive?

### ISSUE THREAD

**Issue by bruno-c** [wiledal/gulp-include#11]
If we have a scenario where

File 1:

``` javascript
//= require myfile.js
//= require someotherfile.js
//= require ../somemodule/main.js
```

somemodule/main.js:

``` javascript
//= require something.js
//= require blah.js
```

We're not going to get all the files from `somemodule/main.js` are we?

**Comment by alexmccabe** [comment]
I can see that this has been merged, but for me this isn't working. I am using Gulp 3.9 and the latest version of gulp-include available. I just get `//=include ../components/setUtils.js` in the source code after compile.

My path through:

`index.js -> [require] ../utils/pluginExists.js -> [require] ../components/setUtils.js`

Am I doing something wrong here?
