### ISSUE TITLE
Set Include Path [Feature Request]

### ISSUE THREAD

**Issue by nicekiwi** [wiledal/gulp-include#14]
Similar to the gulp-sass plugin it'd be great to be able to pass a "IncludePaths" option, so when include runs it looks in the included path as well ass the current location for a file to make things simpler.

**Comment by ifduyue** [comment]
+1 for this feature.

**Comment by xpepermint** [comment]
+1

**Comment by jonnitto** [comment]
There's a fork from my workbuddy, who do exactly this: https://github.com/sbruggmann/gulp-include

**Comment by davidguilherme** [comment]
+1

**Comment by alrayyes** [comment]
+1

**Comment by everett-ppadv** [comment]
+1

**Comment by everett-ppadv** [comment]
@wiledal This feature would be excellent for folks using bower.

**Comment by soneway** [comment]
+1

**Comment by wiledal** [comment]
This has been added in version 2.2.0.

**Comment by everett-ppadv** [comment]
@wiledal Thank you so much!

**Comment by nicekiwi** [comment]
@wiledal awesome! Thanks :+1:
