### ISSUE TITLE
Include tree to not include assets that have already been included

### ISSUE THREAD

**Issue by dwightwatson** [wiledal/gulp-include#20]
Perhaps when using the `include_tree` statement, assets that have previously been included should not be included again.

**Comment by Chamberlain91** [comment]
I second this!

**Comment by blunckr** [comment]
This would be great. I use this feature with sprockets all the time to make sure certain files get loaded before others

**Comment by plurch** [comment]
With sprockets, 'require' statements ensure that a file is only loaded once while 'include' statements allow the same file to be added multiple times. 

I am working on adding this with @yuhuilin here: https://github.com/plurch/gulp-include/tree/require_once

**Comment by wiledal** [comment]
That makes sense, @plurch. Please let me know if you have this working.

**Comment by wiledal** [comment]
This has been implemented in version `2.x.x`

**Comment by plurch** [comment]
We decided to write a pared down module that fits our use-cases (only need support for require directives, ability to pass in glob options) - https://github.com/plurch/gulp-require-file

Thanks for the inspiration @wiledal !
