### ISSUE TITLE
double line

### ISSUE THREAD

**Issue by pabloalmunia** [wiledal/gulp-include#33]
The first "include" create a double return per line.

The followings "include" don't have this problem.

This is the original file:

```javascript
utils.uuid = function uuid(a){
    return a ?
        (a ^ Math.random()*16 >> a/4).toString(16) :
        ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,this.uuid);
};
```

This is the file included:

```js
            utils.uuid = function uuid(a){

                return a ?

                    (a ^ Math.random()*16 >> a/4).toString(16) :

                    ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,this.uuid);

            };
```

**Comment by mehtmehtsen** [comment]
gulp-include seems to have a problem with the line endings. I just "included" a file with CR and LF for line endings, in the final file there are two lines per line.
So in Notepad++ I replaced `\r\n` (CRLF) with `\r` (CR) and recompiled. Everything's fine now. Funny thing: when I just use LFs, I also get two lines.
So I suppose your first file uses CRLF or maybe just LF, the others use CRs.

**Comment by rikjurjens** [comment]
The problem seems to be with the DIRECTIVE_REGEX.
If you use it like this

```
(function() {

})();
```

**Comment by zefirka** [comment]
I think the trouble on [line 79](https://github.com/wiledal/gulp-include/blob/master/index.js#L79), where:
`whitespace = whitespace[0].replace("\n", "");`
This clears only first `\n` from whitespace matches, when for first include it equals to `'\n\n'`, so after it expression `whitespace` is truthy (when we except false).

I've made [pull reques](https://github.com/wiledal/gulp-include/pull/42).

**Comment by wiledal** [comment]
This is fixed in the new version. Closing!

**Comment by Skosiris** [comment]
Getting double lines on v2.0.2 on any require/include command that is preceded by empty lines.

ex: The footer here gets double lines.

	//=include inc/page-header.inc

	test page

	//=include inc/page-footer.inc

Adding something right before the include fixes the problem:

	//=include inc/page-header.inc

	test page

	something
	//=include inc/page-footer.inc

**Comment by jelmerdemaat** [comment]
I'm also getting this issue with version 2.0.2 on Windows. Solved for now by removing blank lines in front of `//=include` statements. But permanent solution would be great!
