### ISSUE TITLE
Fail on file not found

### ISSUE THREAD

**Issue by zachdaniel** [wiledal/gulp-include#37]
Great tool!  I'm a little curious if it is possible to have gulp-include fail, or at least notify me if the file isn't found.  There is no way to verify if files were actually included aside from *looking* at the end result, which is not reliable.

**Comment by PaulNegoescu** [comment]
Also quite interested in this one.

**Comment by wiledal** [comment]
You can catch errors into a simple `console.log`
```
  gulp.src("content/assets-source/js/app.js")
    .pipe(include())
      .on('error', console.log)
    .pipe(gulp.dest("content/assets/js"));
```
This won't warn you specifically, but it should be enough to keep it running in case of an error.

**Comment by kulbakin** [comment]
@wiledal the suggested solution does not help  - there is no error produced in the scenario of referenced file not found.

As original poster suggested, it would be great to have `gulp-include` warn or fail if file specified in `require` directive is not found, currently it just leaves unparsed directive in the result file without any error or warning triggered.

Ideally, it would be great to have an option which would trigger error if referenced file is not found.

**Comment by ranietots32** [comment]
Why did you close this? this issue **has not been solved**.
