### ISSUE TITLE
Include then Webpack

### ISSUE THREAD

**Issue by monkeymonk** [wiledal/gulp-include#38]
Hi there!

I'm trying to use `gulp-include` then `gulp-webpack` ...but not succeed for now.
It seems to ignore the `incude` part... I see my `//= require ./thing.js` in the bundled file.

Is anyone know how to fix this?
###### JS task:

``` javascript
gulp.src(config.src_dir + '/js/main.js')
        .pipe($.include())
        .pipe($.webpack(config.webpack))

        .pipe(gulp.dest(config.public_dir + '/js'));
```
###### `main.js`

``` javascript
console.log('-> main');

//= require ./yepee.js
```
###### `yepee.js`

``` javascript
console.log('ᕕ( ᐛ )ᕗ <( Yepee! )');
```

**Comment by tinyfly** [comment]
Not an answer to your specific question but why not use webpack to require files? It has that built in and it seems like you are trying to duplicate it's functionality.

**Comment by monkeymonk** [comment]
The fact is I wanted to allow using webpack (or not) without making the require functionality dependent ti that choice.

But I think I can use something like [gulp-file](https://www.npmjs.com/package/gulp-file) to do what I want. 

I just do not have the time to try this these days ! ^^'
