### ISSUE TITLE
When is the trailing line break necessary?

### ISSUE THREAD

**Issue by erikreagan** [wiledal/gulp-include#39]
I recently started using gulp-include to bring in multiple types of files (js, css, html snippets) into a final html file for a micro project. I noticed that with every use of `include` there's a new line break at the end of the text included. 

Example, if I use the following:

    <script type="text/javascript">
        //= include includes/scripts.inc.js
    </script>

The last line of my file is simply a `}` but when rendered/included I end up with 

    <script type="text/javascript">
        // ... the rest of my file
        }
        
    </script>

I poked around at the `index.js` file and noticed on [line 87](https://github.com/wiledal/gulp-include/blob/master/index.js#L87) that a line break is added. Is this line break fully necessary?

Thanks!

**Comment by wiledal** [comment]
This should be fixed in the latest version :100:

**Comment by erikreagan** [comment]
Thanks! :trophy:
