### ISSUE TITLE
Indentation is not maintained

### ISSUE THREAD

**Issue by mlenser** [wiledal/gulp-include#41]
When including a HTML file the resulting file does not have the same indentation as the base file. Some of the nesting is broken. Often the first line is 1 indentation less than it should be.

Perhaps this is due to CRLF?

**Comment by wiledal** [comment]
Indentation has been reworked in the new version, are you still experiencing issues?

**Comment by mlenser** [comment]
It indeed seems to be fixed. Thanks!
