### ISSUE TITLE
replace

### ISSUE THREAD

**Issue by Riim** [wiledal/gulp-include#44]
replace
```js
content = content.replace(matches[i], replaceContent);
```
to
```js
content = content.replace(matches[i], function() { return replaceContent; });
```

[specials](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter): $$, $&, $`, $', $n, $nn

```js
'abc'.replace('b', "1$'")
=> "a1cc"

'abc'.replace('b', function() { return "1$'"; })
=> "a1$'c"
```

**Comment by wiledal** [comment]
This has been implemented, thanks!
