### ISSUE TITLE
Arrays no longer works !

### ISSUE THREAD

**Issue by bdecarne** [wiledal/gulp-include#50]
Hi,

First i love your library, i use it in all my angular projects.

With the version 2.x it seems that arrays doesnt work anymore :

```
//=include ["*.js", "!app.js"] 
```

Can you confirm ? I would be sad...

**Comment by wiledal** [comment]
I actually have never seen this before...
Are you certain this worked in 1.x?

`gulp-include` uses straight up `glob`, so anything `glob` can do, we can do.
For this specific situation, you could use something like
```js
//=include !(app.js)
```

**Comment by bdecarne** [comment]
Hi,

Yes, it worked on 1.x.

Look at this code extracted from the 1.1.1 version (https://github.com/wiledal/gulp-include/commit/8bcb7986129703e4103dba863e2ff18780f3d44f#diff-168726dbe96b3ce427e7fedce31bb0bcL120) :

```js
if (relativeFilePath.charAt(0) === '[') {
    relativeFilePath = eval(relativeFilePath);
    for (var i = 0; i < relativeFilePath.length; i++) {
        if (relativeFilePath[i].charAt(0) === '!') {
            negations.push(relativeFilePath[i].slice(1))
        } else {
            globs.push(relativeFilePath[i]);
        }
    }
} else {
    globs.push(relativeFilePath);
}
```

Blaise
