### ISSUE TITLE
Directive Not Working

### ISSUE THREAD

**Issue by geoguide** [wiledal/gulp-include#53]
This is driving me crazy. I put this in my index file

`<!--=include www/app/**/**/*.js -->`
`<!--=include www/app/**/*.js -->`
`<!--=include www/app/*.js -->`
`<!--=include www/templates.js -->`

and have `include       = require("gulp-include");` in my gulpfile. I'm new to gulp, usually use grunt but working on someone else's project. Am I missing something obvious? It just prints out the comments.

**Comment by jeffman78** [comment]
Make sure your directives are on a single line.
