### ISSUE TITLE
gulp-changed not picking up new files

### ISSUE THREAD

**Issue by zslabs** [wiledal/gulp-include#56]
Hi,
Thanks so much for creating this! I've run into a snag now that my src file is just one `main.js` input; [gulp-changed](https://www.npmjs.com/package/gulp-changed) doesn't appear to be picking up any changes from the included files; I running this check after I include that main file. Wanted to see if you had any tips around this or if I'm thinking of this incorrectly. Thanks!

**Comment by wiledal** [comment]
Never used `gulp-changed`. I usually go with a `gulp-watch`-setup:

```js
var gulp = require("gulp"),
    watch = require("gulp-watch"),
    include = require("gulp-include");

gulp.task("js", function() {
  gulp.src("assets-src/js/main.js")
    .pipe(include())
    .pipe(gulp.dest("assets/js"));
});

gulp.task("watch", function() {
  watch("assets-src/js/**/*.js", function() {
    gulp.start("js");
  });
})
```
