### ISSUE TITLE
How to include or require from node_modules?

### ISSUE THREAD

**Issue by zoxon** [wiledal/gulp-include#61]
How to include or require from node_modules?
I use this code `//= require ../../../node_modules/jquery/dist/jquery.js`, but it is not convenient.
I'm try to use webpack or browserify, but they add a lot of unnecessary code.
Thank you

**Comment by Grawl** [comment]
You have to wrap path string into quotes (single `'` or double `"`) like this:

```js
//=require '../../../node_modules/jquery/dist/jquery.js'
```

And the path must be relative to your file where you want include something by path.

**Comment by zoxon** [comment]
@Grawl 
This code work `//= require ../../../node_modules/jquery/dist/jquery.js`
But if I move file path stay wrong.
How to set path from project root or node_modules folder?

**Comment by Grawl** [comment]
See https://github.com/wiledal/gulp-include/issues/14 and https://github.com/wiledal/gulp-include/issues/14#issuecomment-99896859

**Comment by zoxon** [comment]
Thank you

**Comment by wiledal** [comment]
You can now achieve this with the `includePaths` option.

```js
gulp.task("build", function() {
  gulp.src("src/js/app.js")
    .pipe(include({
      includePaths: [
        __dirname + "/src/js",
        __dirname + "/node_modules"
      ]
    }))
      .on("error", console.log)
    .pipe(gulp.dest("dist/js"))
})
```

**Comment by Grawl** [comment]
Awesome, dude! Awesome!
