### ISSUE TITLE
Error preventing run

### ISSUE THREAD

**Issue by D-Bullock** [wiledal/gulp-include#67]
When I use the plugin within Visual Studio 2015, it throws an error:
```
 node_modules\gulp-inject\src\inject\index.js:127
SyntaxError: Unexpected token ,
```

It seems that it doesn't like the unnamed items in the object on that line - when I went into the source and tried naming the properties, the error moved onto the next unnamed property.

**Comment by wiledal** [comment]
Not sure if this is related to `gulp-include`, since the error is happening in `gulp-inject`?

**Comment by D-Bullock** [comment]
Opps...
