### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by trentearl** [wiledal/gulp-include#9]
There is no source map support.

**Comment by Chamberlain91** [comment]
+1 this too...

**Comment by maciekpaprocki** [comment]
source maps would be great improvement. However without that it's still one of the most useful gulp modules!

**Comment by thasmo** [comment]
+1

**Comment by blunckr** [comment]
+1

**Comment by parmactep** [comment]
+1

**Comment by NicolajKN** [comment]
+1

**Comment by tjbenton** [comment]
+1

**Comment by philhaz** [comment]
+1

**Comment by stephanedemotte** [comment]
+1

**Comment by andrewcroce** [comment]
+1 for this

**Comment by sdaitzman** [comment]
:+1:

**Comment by AlexanderFlatscher** [comment]
+1 for https://github.com/floridoo/gulp-sourcemaps integration

**Comment by noisyneuron** [comment]
+1

**Comment by wiledal** [comment]
Closing as this has now been merged, thanks [vetruvet](https://github.com/vetruvet) :beer:

**Comment by thasmo** [comment]
Nice, thanks! :)

**Comment by DevNIX** [comment]
As noted in the pull request, sourcemaps will not work with UglifyJS. Is there any alternative supporting sourcemaps with gulp-include?
